pubspec.yaml
name: user_app
description: Taiga Ecommerce User App - Flutter application for customers

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  
  # Networking
  http: ^1.1.0
  dio: ^5.3.2
  
  # Local Storage
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  
  # UI Components
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.0
  carousel_slider: ^4.2.1
  shimmer: ^3.0.0
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.9
  firebase_auth: ^4.15.3
  
  # Payment Gateways
  google_pay: ^2.0.0
  pay: ^1.1.0
  
  # Utilities
  intl: ^0.18.1
  image_picker: ^1.0.4
  url_launcher: ^6.2.1
  geolocator: ^10.1.0
  permission_handler: ^11.1.0
  connectivity_plus: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Schyler
      fonts:
        - asset: fonts/Schyler-Regular.ttf
        - asset: fonts/Schyler-Italic.ttf
          style: italic